### PR TITLE
Update environment page URL

### PR DESCRIPTION
**Pull request by rajiesh**

### CODE REVIEW

**Comment by ketan** [comment]
I should think we should consider adding a redirect in the app to retain
the old URL, for some time?

**Comment by rajiesh** [comment]
@ketan You are considering retaining old URL to help users who may have bookmarked it?

**Comment by varshavaradarajan** [comment]
@ketan - https://github.com/gocd/gocd/pull/5113#issuecomment-418454754

**Comment by varshavaradarajan** [comment]
And https://github.com/gocd/gocd/pull/4157#issuecomment-356135842

**Pull request merged**
